language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - 2.3.1
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
